server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: redireciona rotas para o index (Angular router em modo path).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
